version: "3.6"

services:
  localstack:
    container_name: localstack-1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4567-4583:4567-4583"
    environment:
      - SERVICES=sns,sqs,dynamodb, s3
      - HOSTNAME_EXTERNAL=localstack-1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEBUG=true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
